### ISSUE TITLE
Make the Preview more beautiful 

### ISSUE THREAD

**Issue by rahul-rb-frontend** [RahulBRB/ID-Card-Generator#2]
Use CSS to make the preview look much better. Currently it is only basic styling.

**Comment by priyamaggarwal18** [comment]
Hello @RahulBRB, I think I can work on improvement in its CSS. So please assign this issue to me.
Also, please mark this issue as Hacktoberfest and Hacktoberfest accepted tag.

**Comment by rahul-rb-frontend** [comment]
Done
